### ISSUE TITLE
Sound will be streamed to the default audio out

### ISSUE THREAD

**Issue by Nastras** [m-reiniger/homebridge-radioplayer#1]
Hallo,

ich gehe mal davon aus das du Deutsch sprechen kannst wenn du als Stream 1 Live gewählt hast😀

Dein Plugin hört sich sehr Interessant an, habe es aber noch nicht getestet.

Kannst du eventuell sagen welchen Audio Out du genau meinst. Denn vom Pi oder kann das Signal gestreamt werden ?

Gruß Nastra

**Comment by m-reiniger** [comment]
Hi, 

der Sound wird an die default sound device bzw. ans audio backend vom jeweiligen OS ausgegeben.

Ich lasse das ganze auf einem alten Mac laufen. Sound geht über Core Audio an die eingestellte Sound Device (Internal Speaker oder Airplay). Von dort aus geht es dann via Airplay an meine Boxen in der ganzen Wohnung.

Ich verwende dieses Paket für die Soundausgabe: https://www.npmjs.com/package/speaker

Vielleicht hilft dir das weiter.
